### ISSUE TITLE
Minizip fails to extract password protected zip file 

### ISSUE THREAD

**Issue by pp771** [nmoinvaz/minizip#527]
We are observing that minizip is failing to extract a password-protected file, even if a valid password is provided.
In case of an invalid password, the library throws an error stating invalid password.
Need to look into this issue ASAP.

We are observing this issue on the Windows version of the library.

**Comment by nmoinvaz** [comment]
You will have to provide more details.

**Comment by pp771** [comment]
Can you tell me under which scenario "PASSWORD_ERROR" is thrown, we get error code '8' for "PASSWORD_ERROR"?
We have confirmed that Winzip is successfully able to extract the file using the same password.

**Comment by nmoinvaz** [comment]
That is not a error number I am familiar with.

**Comment by pp771** [comment]
Ignore the earlier message, The error number is -108 i.e. MZ_PASSWORD_ERROR(-108).
And the api failing is **unzOpenCurrentFilePassword(uf, password);**.
The API is expected to return UNZ_OK(0).

**Comment by pp771** [comment]
<img width="722" alt="Screenshot 2020-10-26 at 11 31 49 AM" src="https://user-images.githubusercontent.com/73294834/97140693-327adf00-1783-11eb-9b57-ff32465d76fe.png">

**Comment by nmoinvaz** [comment]
What version of the library are you using? What type of encryption is the zip using?

**Comment by pp771** [comment]
There is no issue when encrypted using minizip. The issue is with other libs encryption.

**Comment by pp771** [comment]
The issue is observed with "2.9.1", "2.10.0".

**Comment by pp771** [comment]
As per xceed API, by default algo is "xemCompatible". We do not set anything explicitly.

**Comment by nmoinvaz** [comment]
I don't use Xceed.

**Comment by Eswcvlad** [comment]
I actually have the same issue after trying to upgrade from 1.2 to the latest version with both legacy and new APIs and it seems like I've figured out, what is causing it.

Here is an example archive (password is "123"):
[compressed.zip](https://github.com/nmoinvaz/minizip/files/5605306/compressed.zip)

It is encrypted with basic ZipCrypto, has data descriptors and NTFS file time extra fields.

Decryption is actually correct, but the problem is in the verification. It _should_ use bytes from the original "last mod file date/time" fields in the local file header, but instead it uses the converted file_info.modified_date as the baseline, which can get overwritten from NTFS/UNIX time extra fields. And, as an example in the archive above, timezone is different in the NTFS extra field, so there is a mismatch.

So, as expected, when I comment the 
`mz_zip_ntfs_to_unix_time(ntfs_time, &file_info->modified_date);`
line in mz_zip.c it works fine as it starts using the original field for verification.

**Comment by nmoinvaz** [comment]
Hmm. I'm not sure how I want to fix that. I don't want to add a new field for `modified_time` file `mz_file_info`.

**Comment by nmoinvaz** [comment]
This should be resolved in the `dev` branch now.

**Comment by Eswcvlad** [comment]
Looks like it fixed the issue for me. Thanks!

Not sure though, if it is the same issue @pp771 was having.

**Comment by pp771** [comment]
This issue is not fixed for our encrypted files. We still get the -102 error code with the latest Minizip 3.0 version. However, the same encrypted files are getting decrypted using other libs and tools like Zip-archive, Winrar.
Please look into this.

**Comment by nmoinvaz** [comment]
Please provide an example zip and more debug info.

**Comment by nmoinvaz** [comment]
Also feel free to track down the issue yourself and submit a PR.

**Comment by kippler** [comment]
Hello. I'm a developer of Bandizip.

It's a Info-zip's modification of bit3.

I made a sample zip file has same problem using this commandline in Ubuntu.

> zip -e  -X infozip.zip a.txt b.txt
[infozip.zip](https://github.com/kippler/Samples/blob/master/sample_files/zip.general-purpose-bit-flag-3/infozip.zip) 

This is the comment for the bit3 in 7zip source.

>           /* Info-ZIP modification to ZipCrypto format:
>                if bit 3 of the general purpose bit flag is set,
>                it uses high byte of 16-bit File Time.
>              Info-ZIP code probably writes 2 bytes of File Time.
>              We check only 1 byte. */

**Comment by nmoinvaz** [comment]
Can you submit a PR?
